<?php


function contact_event_organiser_node_view($node, $view_mode, $langcode) {

	//if this is not the full view of a event content type, then return
	if($node->type!='event' OR $view_mode!='full'){
		return;
	};
	
	if(!(isset($node->field_email['und'][0]['email']) && ($node->field_email['und'][0]['email']!=''))){
		return;
	};
	
	$node->content['contact_event_organiser_form']=array(
		'#markup' => drupal_render(drupal_get_form('contact_event_organiser_form', $node)),
		'#weight' => 10
	);
	$node->content['contact_event_organiser_title']=array(
		'#markup' => '<h3>Contact event organiser</h3',
		'#weight' => 9
	);
	
}

function contact_event_organiser_form($form, &$form_state, $node){
	$form['name'] = array(
		'#title' => 'Name',
		'#type' => 'textfield',
		'#description' => 'Your name is required.',
		'#required' => TRUE,
	);
	$form['email'] = array(
		'#title' => 'Email address',
		'#type' => 'textfield',
		'#description' => 'Your email address is required.',
		'#required' => TRUE,
	);
	$form['text'] = array(
		'#title' => 'More info',
		'#type' => 'textarea',
		'#description' => 'Optionally use this space to ask questions and include extra information.',
	);
	$form['nid'] = array(
		'#type' => 'hidden',
		'#value' => $node->nid
	);
	$form['sumbit'] = array(
		'#type' => 'submit',
		'#value' => t('Send email to organiser'),
	);
	return $form;
}

function contact_event_organiser_form_validate($form, $form_state){
	if ($form_state['values']['email'] && !valid_email_address($form_state['values']['email'])) {
	    form_set_error('email', t('The e-mail address you specified is not valid.'));
		return;
	}
//    form_set_error('email', t('The e-mail address you specified is totally poop!'));

}

function contact_event_organiser_form_submit($form, $form_state){
	global $account;
	
	$node=node_load($form_state['values']['nid']);
	
	$params['from']=$form_state['values']['email'];
	$params['cc']=$form_state['values']['email'];	
	$params['to']=$node->field_email['und'][0]['email'];
	$params['subject']="LQ website event enquiry for {$node->title}";
	
	$params['body']="
Enquiry from: '{$form_state['values']['name']}'
Email address: '{$form_state['values']['email']}'
Regarding event: '{$node->title}'
Extra info: '{$form_state['values']['text']}'
";
	
	drupal_mail('contact_event_organiser', 'notice', $params['to'], user_preferred_language($account), $params);
    drupal_set_message("Your email has been sent and copied to the address that you specified above ({$form_state['values']['name']}).");
}

function contact_event_organiser_mail($key, &$message, $params) {
	
	$message['to'] = $params['to'];
	$message['subject'] = $params['subject'];
	$message['body'][] = $params['body'];
	$message['from'] = $params['from'];
	$message['headers']=array('Cc' => $params['cc']);
	
}



