<?php
/*
 * Implements hook_block_info().
 *
 * Tells drupal that we are providing a custom block in this module.
 */
function thought_sense_block_info(){
	$blocks['meeting-menu'] = array(
	    'info' => t('Meeting menu'), 
	    'cache' => DRUPAL_NO_CACHE,
  	);
  	return $blocks;
}

/*
 * Implements hook_block_view().
 *
 * Creates a special block for meeting pages.
 * Meeting pages are those with this style of url:
 * londonquakers.org.uk/meeting/blackheath
 *
 * The 'Meeting menu' block is configured in the UI to appear
 * on pages where the path is 'meeting/*'
 */
function thought_sense_block_view($delta = '') {
  $path_array=explode('/', $_SERVER['REQUEST_URI']);
  // $path_array[1] = meeting
  // $path_array[2] = blackheath
	if(!isset($path_array[2])){
		return;
  }
  // Note that meeting/blackheath is an alias for node/3
  // Even if the url is londonquakers.org.uk/meeting/blackheath,
  // arg(0) will contain 'node' and arg(1) will contain '3'.
	if ( arg(0) == 'node' && is_numeric(arg(1)) && !arg(2) ) {
		$node = node_load(arg(1));
		if($node->type == 'meeting'){
      $nid = $node->nid;
      $title = $node->title;
		}
    if($node->type == 'meeting_page') {
      // find the meeting to which this meeting page belongs
      // and get its nid
      $nid = $node->field_member_of_meeting['und'][0]['nid'];
      $meeting_nid = node_load($nid);
      $title = $meeting_nid->title;
    }
	}
  if(!isset($nid)){
		// deal with urls like meeting/3/events
    $nid = $path_array[2];
    $node = node_load($nid);
    $title = $node->title;
	}
	if (($path_array[1]=='meeting') || (($path_array[1]=='node') && (($node->type == 'meeting') || ($node->type == 'meeting_page')))) {	

    // find out if this meeting has any meeting pages
    $query = new EntityFieldQuery;
    $query
      ->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'meeting_page')
      ->fieldCondition('field_member_of_meeting', 'nid', $nid, '=');
    $result = $query->execute();

    if ($result) {
      // entity_load takes an array of node ids
      $pages = entity_load('node', array_keys($result['node']));
      foreach($pages as $page) {
        $page_nid = $page->nid;
        $page_title = $page->title;
        $pages_html .= "<li><a href='/node/$page_nid'>$page_title</a></li>";
      }
    }

		$block = array();
		switch ($delta) {
			case 'meeting-menu':
        //$block['subject'] = t('Meeting menu');
        $block['content'] = "
        <ul>
        <li><a href='/node/{$nid}'>$title Meeting</a></li>
        <li><a href='/meeting/{$nid}/events'>Events</a></li>
        <li><a href='/meeting/{$nid}/rooms'>Rooms for Hire</a></li>
        $pages_html
        <li><a href='/'>Back to London Quakers</a></li>
        </ul>";
        // This sets the site_name temporarily.
        // see: drupal.org/node/253447
        $GLOBALS['conf']['site_name'] = "$title Quaker Meeting";
        break;
		}
		return $block;
	}
}
