<?php
function redirect_6wm_boot(){
  //Note that when hook_boot is called, drupal goto is not definied, hence we are using the following method instead: heaader("Location: http://www.example.com/");exit; 
  $lqpt_host = 'www.lqpt.org.uk';
  $lq_host = 'www.londonquakers.org.uk';
  $host = $_SERVER['HTTP_HOST'];
  $uri = $_SERVER['REQUEST_URI'];
  $uri_parts=explode('/', $uri);
  $uri_start=$uri_parts[1];
  //If we are at '/' on the London Quaker Property Trust home page, we probably want to be redirected to /lqpt
  if($uri=="/" AND $host==$lqpt_host){
    header("Location: http://{$lqpt_host}/lqpt");
    exit;
  }
  //Else if the first part of the URI is lqpt and we are not on the lqpt domain, the we should redirect to lqpt domain
  elseif($uri_start=='lqpt' AND $host!=$lqpt_host ){
    header("Location: http://{$lqpt_host}{$uri}");
    exit;
  }
  //Else if the first part of the URI is not lqpt and we are not on the lq domain then we should redirect to the lq domain
  elseif($uri_start!='lqpt' AND $host!=$lq_host ){
    header("Location: http://{$lq_host}{$uri}");
    exit;
  }
}
?>
