<?php
function redirect_6wm_boot(){
  //Note that when hook_boot is called, drupal goto is not definied, hence we are using the following method instead: heaader("Location: http://www.example.com/");exit; 
  $swm_host = 'www.6wm.org.uk';
  $lq_host = 'www.londonquakers.org.uk';
  $swm_start = '6';

  if(
    $_SERVER['HTTP_HOST']!=$swm_host AND
    $_SERVER['HTTP_HOST']!=$lq_host AND
    $_SERVER['HTTP_HOST']!='6wm.org.uk'// TODO - could change this to ends in 6wm.org.uk, etc. to make it more robust
    AND $_SERVER['HTTP_HOST']!='londonquakers.org.uk' // TODO - could change this to ends in londonquakers.org.uk, etc. to make it more robust
  ){ 
    return;
  }
  
  $host = $_SERVER['HTTP_HOST'];
  $uri = $_SERVER['REQUEST_URI'];

  $uri_parts=explode('/', $uri);
  $uri_start=$uri_parts[1];
  //If we are at '/' on the London Quaker Property Trust home page, we probably want to be redirected to /swm
  if($uri=="/" AND $host==$swm_host){
    header("Location: http://{$swm_host}/{$swm_start}");
    exit;
  }
  //Else if the first part of the URI is swm and we are not on the swm domain, the we should redirect to swm domain
  if($uri_start==$swm_start AND $host!=$swm_host ){
    header("Location: http://{$swm_host}{$uri}");
    exit;
  }
  //Else if the first part of the URI is not swm and we are not on the lq domain then we should redirect to the lq domain
  if($uri_start!=$swm_start AND $host!=$lq_host ){
    header("Location: http://{$lq_host}{$uri}");
    exit;
  }
}

function redirect_6wm_preprocess_page(&$variables){
  if($_SERVER['HTTP_HOST']=='www.6wm.org.uk'){
    $variables['site_name']='Six Weeks Meeting';
  }
}

function redirect_6wm_preprocess_html(&$variables){
  if($_SERVER['HTTP_HOST']=='www.6wm.org.uk'){
    $variables['head_title']=str_replace(' | London Quakers', ' | Six Weeks Meeting', $variables['head_title']);
  }
}

